import Image from "next/image";
import { CtaStrip } from "@/components/cta-strip";
import { IconArrowUpRight, IconCheck } from "@/components/icons";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { facilities } from "@/data/features";

export default function FacilitiesPage() {
  return <main>
    <PageHero eyebrow="The place around the lesson" current="Campus life" title={<>A calm space for <em>serious</em> learning.</>} text="The best classroom is not the fanciest one. It is the room where students feel comfortable enough to focus, ask and try again." image="/images/about/classroom.jpg" imageAlt="Bright classroom prepared for science learning" />
    <section className="page-section"><div className="shell"><SectionHeading eyebrow="Made for learning" title={<>Every detail has a <em>purpose.</em></>} text="From the way a room catches morning light to the way a student can find the right resource, our campus is designed around attention." /><div className="card-grid-4" style={{ marginTop: "48px" }}>{facilities.map((facility) => <article className="feature-card" key={facility.title}><div className="feature-image"><Image src={facility.image} alt={facility.title} fill sizes="(max-width: 760px) 100vw, 25vw" /></div><div className="feature-body"><p className="feature-tag">{facility.meta}</p><h3>{facility.title}</h3><p>{facility.text}</p></div></article>)}</div></div></section>
    <section className="page-section warm"><div className="shell split-grid"><div className="split-image"><Image src="/images/features/concept-learning.jpg" alt="Teacher using a physical model with students" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="split-copy"><p className="eyebrow">A room that listens</p><h2>Learning happens between the <em>lines.</em></h2><p>Some of the most important moments happen after class — around a diagram, over a half-finished question or in the quiet decision to try once more.</p><ul className="numbered-list"><li className="numbered-item"><b>01</b><div><strong>Warm, bright classrooms</strong><p>Comfortable spaces that help students stay present and engaged.</p></div></li><li className="numbered-item"><b>02</b><div><strong>Resources within reach</strong><p>Notes, models and practice material ready when curiosity arrives.</p></div></li><li className="numbered-item"><b>03</b><div><strong>People who notice</strong><p>Mentors who see the small wins and the moments that need support.</p></div></li></ul></div></div></section>
    <section className="page-section white"><div className="shell split-grid"><div className="split-copy"><p className="eyebrow">Come by for a visit</p><h2>See the room before you make a <em>decision.</em></h2><p>We are happy to show families around, talk through the daily rhythm and answer the practical questions that matter.</p><ul className="intro-points"><li><IconCheck size={17} /> Near Baragada main road</li><li><IconCheck size={17} /> Weekday visits welcome</li></ul><a href="/contact" className="button button-red">Plan your visit <IconArrowUpRight size={17} /></a></div><div className="split-image"><Image src="/images/contact/institute.jpg" alt="Vidyashree institute building and learning space" fill sizes="(max-width: 760px) 100vw, 50vw" /></div></div></section>
    <CtaStrip title="The right environment can change the whole experience." text="Come see our campus and tell us what your student needs from their next learning space." action="Plan a visit" href="/contact" />
  </main>;
}
