import Image from "next/image";
import { CtaStrip } from "@/components/cta-strip";
import { IconArrowUpRight, IconCheck } from "@/components/icons";
import { PageHero } from "@/components/page-hero";
import { StatBand } from "@/components/stat-band";

export default function AchievementsPage() {
  return <main>
    <PageHero eyebrow="Progress worth celebrating" current="Achievements" title={<>The result is more than a <em>number.</em></>} text="We care about strong results because they open doors. We care about the growth behind them because it stays with students much longer." image="/images/achievements/result-day.jpg" imageAlt="Students celebrating an academic milestone" action={{ label: "Talk about goals", href: "/enquiry" }} />
    <StatBand dark />
    <section className="achievement-statement"><div className="shell achievement-grid"><div className="achievement-copy"><p className="eyebrow">A wider definition of success</p><h2>When effort finds a <em>method,</em> progress follows.</h2><p>Our students work hard. Our job is to make that hard work more effective — with better foundations, better feedback and a team that stays close to the process.</p><ul className="intro-points"><li><IconCheck size={17} /> Board-ready understanding</li><li><IconCheck size={17} /> Stronger study habits</li><li><IconCheck size={17} /> More confident problem solving</li><li><IconCheck size={17} /> A plan for what comes next</li></ul></div><div className="achievement-image"><Image src="/images/achievements/result-day.jpg" alt="Students and teacher celebrating a result day" fill sizes="(max-width: 760px) 100vw, 40vw" /><div className="achievement-badge"><div><strong>96%</strong><span>distinction<br />rate</span></div></div></div></div></section>
    <section className="achievement-tables"><div className="shell achievement-table-grid"><div><p className="eyebrow eyebrow-light">Recent milestones</p><h2>Work that turns into <em>momentum.</em></h2><div className="table-list"><div className="table-row"><span>Board distinction rate</span><strong>96%</strong></div><div className="table-row"><span>Students with improved confidence</span><strong>9 / 10</strong></div><div className="table-row"><span>Families recommending Vidyashree</span><strong>94%</strong></div><div className="table-row"><span>Years of steady teaching</span><strong>12+</strong></div></div></div><div><p className="eyebrow eyebrow-light">What we measure too</p><h2>The things a mark sheet <em>cannot.</em></h2><div className="table-list"><div className="table-row"><span>Questions asked in class</span><strong>↑</strong></div><div className="table-row"><span>Students building their own plans</span><strong>↑</strong></div><div className="table-row"><span>Parents feeling informed</span><strong>↑</strong></div><div className="table-row"><span>Fear of getting it wrong</span><strong>↓</strong></div></div></div></div></section>
    <section className="page-section white"><div className="shell split-grid"><div className="split-image"><Image src="/images/hero/students-study.jpg" alt="Students studying with focus" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="split-copy"><p className="eyebrow">The next result</p><h2>It starts with knowing where to <em>begin.</em></h2><p>Bring us the goal, the worry or the question. Together, we’ll make the route ahead feel more visible.</p><a href="/enquiry" className="button button-red">Build a plan <IconArrowUpRight size={17} /></a></div></div></section>
    <CtaStrip title="Your progress deserves a thoughtful plan." text="Start with a conversation about the student behind the result." />
  </main>;
}
